### ISSUE TITLE
How to verify authenticity of webhook call with HMAC hash?

### ISSUE THREAD

**Issue by beefcakefu** [hit-pay/php-sdk#3]
Hi,

I am having trouble generating a HMAC hash that matches the webhook request parameter. Adapting from `Client::generateSignatureArray` (these are sandbox values):

```
<?php

$salt = 'tGuQq3FpFh9g5qlqXbchSni4tvlOjUs5XzfUXuH6rGsG853WCWVqT8Notg4Ra9hO';
$args = array(
	"payment_id" => "96ac23e7-2971-455e-9c18-79a4953eeb90",
	"payment_request_id" => "96ac23e5-8447-4301-ada6-5c104bd23679",
	"phone" => "",
	"amount" => "500.00",
	"currency" => "SGD",
	"status" => "completed"
//	"hmac" => "825fe7dceec867c54c837292873d8e74ad2567a0538e4ac13c027de09602cbed"
);

$hmacSource = [];

foreach ($args as $key => $val) {
	$hmacSource[$key] = "{$key}{$val}";
}

ksort($hmacSource);

$sig = implode("", array_values($hmacSource));

$calculatedHmac = hash_hmac('sha256', $sig, $salt); 

var_dump($calculatedHmac);
// This results in: string '4d7a513e32621ad19363f97329ce37abbaf4550204cbb60f1b4824cdae60a091' (length=64)
?>
```

Could we get some example code for HMAC verification please?

**Comment by musthakeem** [comment]
It seems you have missed reference_number from the values, as per documentation you have to use the reference_number, even if it is empty you have to use an empty string value.

```
$args = array(
	"payment_id" => "96ac23e7-2971-455e-9c18-79a4953eeb90",
	"payment_request_id" => "96ac23e5-8447-4301-ada6-5c104bd23679",
	"phone" => "",
	"amount" => "500.00",
	"currency" => "SGD",
	"status" => "completed",
	"reference_number" => ""
);
```

From [documentation](https://hit-pay.com/docs.html#webhook-fields)
**Signature Mismatch?**
Possible reasons for wrong hmac value generated

- Ensure that you are using the correct salt value from the correct environment (Sandbox or Production)
- Make sure not to include the hamc value when calculating the hmac
- Make sure all the values stated above are included in the payload including reference_number. Use empty string if the value does not exist

**Comment by beefcakefu** [comment]
Thank you @musthakeem, that was indeed what was missing! Getting the correct HMAC hash now.
